
package support;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TeamWS", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TeamWS {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTeams", targetNamespace = "http://server/", className = "support.GetTeams")
    @ResponseWrapper(localName = "getTeamsResponse", targetNamespace = "http://server/", className = "support.GetTeamsResponse")
    @Action(input = "http://server/TeamWS/getTeamsRequest", output = "http://server/TeamWS/getTeamsResponse")
    public List<String> getTeams();

    /**
     * 
     * @param arg0
     * @return
     *     returns support.Team
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTeam", targetNamespace = "http://server/", className = "support.GetTeam")
    @ResponseWrapper(localName = "getTeamResponse", targetNamespace = "http://server/", className = "support.GetTeamResponse")
    @Action(input = "http://server/TeamWS/getTeamRequest", output = "http://server/TeamWS/getTeamResponse")
    public Team getTeam(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
