
package support;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TeamWSImplService", targetNamespace = "http://impl.server/", wsdlLocation = "http://127.0.0.1:9999/TeamWS?wsdl")
public class TeamWSImplService
    extends Service
{

    private final static URL TEAMWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TEAMWSIMPLSERVICE_EXCEPTION;
    private final static QName TEAMWSIMPLSERVICE_QNAME = new QName("http://impl.server/", "TeamWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/TeamWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEAMWSIMPLSERVICE_WSDL_LOCATION = url;
        TEAMWSIMPLSERVICE_EXCEPTION = e;
    }

    public TeamWSImplService() {
        super(__getWsdlLocation(), TEAMWSIMPLSERVICE_QNAME);
    }

    public TeamWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEAMWSIMPLSERVICE_QNAME, features);
    }

    public TeamWSImplService(URL wsdlLocation) {
        super(wsdlLocation, TEAMWSIMPLSERVICE_QNAME);
    }

    public TeamWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEAMWSIMPLSERVICE_QNAME, features);
    }

    public TeamWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TeamWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TeamWS
     */
    @WebEndpoint(name = "TeamWSImplPort")
    public TeamWS getTeamWSImplPort() {
        return super.getPort(new QName("http://impl.server/", "TeamWSImplPort"), TeamWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TeamWS
     */
    @WebEndpoint(name = "TeamWSImplPort")
    public TeamWS getTeamWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.server/", "TeamWSImplPort"), TeamWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEAMWSIMPLSERVICE_EXCEPTION!= null) {
            throw TEAMWSIMPLSERVICE_EXCEPTION;
        }
        return TEAMWSIMPLSERVICE_WSDL_LOCATION;
    }

}
