
package support;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImageWSImplService", targetNamespace = "http://impl.server/", wsdlLocation = "http://127.0.0.1:9999/ImageWS?wsdl")
public class ImageWSImplService
    extends Service
{

    private final static URL IMAGEWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMAGEWSIMPLSERVICE_EXCEPTION;
    private final static QName IMAGEWSIMPLSERVICE_QNAME = new QName("http://impl.server/", "ImageWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9999/ImageWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMAGEWSIMPLSERVICE_WSDL_LOCATION = url;
        IMAGEWSIMPLSERVICE_EXCEPTION = e;
    }

    public ImageWSImplService() {
        super(__getWsdlLocation(), IMAGEWSIMPLSERVICE_QNAME);
    }

    public ImageWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMAGEWSIMPLSERVICE_QNAME, features);
    }

    public ImageWSImplService(URL wsdlLocation) {
        super(wsdlLocation, IMAGEWSIMPLSERVICE_QNAME);
    }

    public ImageWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMAGEWSIMPLSERVICE_QNAME, features);
    }

    public ImageWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImageWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImageWS
     */
    @WebEndpoint(name = "ImageWSImplPort")
    public ImageWS getImageWSImplPort() {
        return super.getPort(new QName("http://impl.server/", "ImageWSImplPort"), ImageWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImageWS
     */
    @WebEndpoint(name = "ImageWSImplPort")
    public ImageWS getImageWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.server/", "ImageWSImplPort"), ImageWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMAGEWSIMPLSERVICE_EXCEPTION!= null) {
            throw IMAGEWSIMPLSERVICE_EXCEPTION;
        }
        return IMAGEWSIMPLSERVICE_WSDL_LOCATION;
    }

}
